repos:
  - repo: local
    hooks:
      - id: format
        name: Format code
        entry: make format
        language: system
        always_run: true
        pass_filenames: false
      - id: lint
        name: Lint code
        entry: make lint
        language: system
        always_run: true
        pass_filenames: false